Major refactoring of the library
This makes ApeTag an opaque type.  The ApeTag struct has been
renamed to sApeTag and moved into the .c file, and now ApeTag
is a pointer to it.  So all users need to switch from using
ApeTag* to ApeTag.

Since ApeTag is now an opaque type, some accessors have been
added for getting information out of it:

ApeTag_get_field: Get single field by key
ApeTag_get_fields: Get all fields in an array
ApeTag_size: Get total size of tag
ApeTag_item_count: Get number of items in the tag
ApeTag_error: Get message related to last error

Other than ApeTag_error, the methods generally should be
called after ApeTag_parse fills in the necessary data.

Callers of ApeTag_get_fields are responsible for freeing the
updated pointer.

While refactoring, reduce duplication in the internals using
a couple of new macros.  Switch to using memset in ApeTag_new
since it should perform better and results in cleaner code.
Switch ApeTag__lookup_genre to take an ApeItem* instead of a
DBT*.

Also, fix the default ID3 genre id used if a genre is present
but it does not match an existing ID3 genre.